name: build
on:
  push:
    branches:
      - master
      - main
  pull_request:
     branches:
      - master
      - main
jobs:
  golangbuild:
    strategy:
      matrix:
        go: [1.18]
        os: [unbuntu-latest]
    name: build
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Build
        run: go build -v ./...    

      
