name: build
on:
  push:
    branches:
      - master
      - main
  pull_request:
     branches:
      - master
      - main
jobs:
  golangbuild:
    strategy:
      matrix:
        go: [1.18]
        os: [unbuntu-latest]
    name: build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3
      - name: golang-build
        run : go build -v ./...