name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

   - name : Install goreportcard tool
   - run: |
          go get github.com/gojp/goreportcard 
          cd goreportcard 
          go install ./vendor/github.com/alecthomas/gometalinter
          go install ./vendor/golang.org/x/lint/golint
          go install ./vendor/github.com/fzipp/gocyclo/cmd/gocyclo
          go install ./vendor/github.com/gordonklaus/ineffassign
          go install ./vendor/github.com/client9/misspell/cmd/misspell
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install ./cmd/goreportcard-cli

   - name: Run Tools
   - run: | 
          goreportcard-cli ./...
          staticcheck ./...

   
