name: Audit

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Verify dependencies
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Run go vet
      run: go vet ./...

    - name : Install goreportcard tool
      run: |
          
          go install github.com/alecthomas/gometalinter@latest
          go install golang.org/x/lint/golint@latest
          go install github.com/fzipp/gocyclo/cmd/gocyclo@latest
          go install github.com/gordonklaus/ineffassign@latest
          go install github.com/client9/misspell/cmd/misspell@latest
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/gojp/goreportcard/cmd/goreportcard-cli@latest

    - name: Run Tools
      run: | 
          goreportcard-cli ./...
          staticcheck ./...

   
