name: golangci-lint
on:
  push:
    branches:
      - master
      - main
      - testing/*
  pull_request:
    branches:
      - master
      - main
      - testing/*
permissions:
  contents: read
jobs:
  name: golangci
  golangci:
    strategy:
      matrix:
        go: [1.17, 1.18]
        os: [macos-latest, windows-latest, ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - uses: actions/checkout@v3

      - name: go build
        run:  go build ./...

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest